# WARNING:
# Do not use this file as a template for you repository TravisCI configuration
# Instead use the files under the "/sample_files" directory for that purpose.
language: python
sudo: false
cache: pip

build_image: vauxoo/odoo-80-image-shippable-auto
commit_container: cowardvassal/vauxoo-dev

python:
  - "2.7"

addons:
  apt:
    packages:
      - expect-dev  # provides unbuffer utility
      - python-lxml  # because pip installation is slow
      - python-simplejson
      - python-serial
      - python-yaml

virtualenv:
  system_site_packages: true

env:

  global:
  - VERSION="8.0" TESTS="1" LINT_CHECK="0"

  matrix:
  - INSTANCE_ALIVE="1" INCLUDE="broken_module" SERVER_EXPECTED_ERRORS="1" PG_LOGS_ENABLE="1" PG_NON_DURABILITY="1" # test errors are detected
  - EXCLUDE="broken_module,broken_lint" OPTIONS="--log-level=debug" INSTALL_OPTIONS="--log-level=info" RUN_COMMAND_MQT_CREATE_FOLDER='mkdir /tmp/tests' PG_LOGS_ENABLE="1" PG_NON_DURABILITY="1"
  - INCLUDE="test_module,second_module" UNIT_TEST="1" PG_LOGS_ENABLE="1" PG_NON_DURABILITY="1" 
  - VERSION="7.0" INCLUDE="test_module,second_module" ODOO_REPO="OCA/OCB" PG_LOGS_ENABLE="1" PG_NON_DURABILITY="1"  # ODOO_REPO usage example
  # - VERSION="6.1" INCLUDE="test_module,second_module"
  - LINT_CHECK="1" TESTS="0" PYLINT_EXPECTED_ERRORS="25" TRAVIS_PULL_REQUEST="false" # Use main pylint config file
  - VERSION="master" LINT_CHECK="1" TESTS="0" PYLINT_EXPECTED_ERRORS="60" TRAVIS_PULL_REQUEST="true"  # Use PR pylint config file
  - VERSION="7.0" LINT_CHECK="1" TESTS="0" PYLINT_EXPECTED_ERRORS="49" TRAVIS_PULL_REQUEST="true"  # To check pylint_conf of PR's with old api

install:
  - cp -r ../maintainer-quality-tools/ $HOME
  - cp -r tests/test_repo/* ./
  - export PATH=$HOME/maintainer-quality-tools/travis:$PATH
  - LINT_CHECK="1" TESTS="1" travis_install_nightly  # self_tests use pylint plugin
  - git --git-dir=${TRAVIS_BUILD_DIR}/.git add --all  # All modules moved are modules changed to test PR changes

script:
  - coverage run --append ./travis/self_tests
  - coverage run --append ./travis/travis_run_tests 8.0  # only used if VERSION not set in env

after_success:
  - travis_after_tests_success
