# WARNING:
# Do not use this file as a template for you repository TravisCI configuration
# Instead use the files under the "/sample_files" directory for that purpose.
language: python
sudo: false
cache:
  apt: true
  directories:
    - $HOME/.cache/pip

build_image: vauxoo/odoo-80-image-shippable-auto
commit_container: cowardvassal/vauxoo-dev

python:
  - "2.7"

addons:
  apt:
    packages:
      - expect-dev  # provides unbuffer utility
      - python-lxml  # because pip installation is slow
      - python-simplejson
      - python-serial
      - python-yaml

virtualenv:
  system_site_packages: true

env:

  global:
  - VERSION="8.0" TESTS="1" LINT_CHECK="0"
  - PYLINT_ODOO_JSLINTRC="$HOME/maintainer-quality-tools/travis/cfg/.jslintrc"
  matrix:
  - INSTANCE_ALIVE="1" INCLUDE="broken_module" SERVER_EXPECTED_ERRORS="1" PG_LOGS_ENABLE="1" PG_NON_DURABILITY="1" WKHTMLTOPDF_VERSION="0.12.4" # test errors are detected and check WKHTMLTOPDF_VERSION
  - EXCLUDE="broken_module,broken_lint" OPTIONS="--log-level=debug" INSTALL_OPTIONS="--log-level=info" RUN_COMMAND_MQT_CREATE_FOLDER='mkdir /tmp/tests' PG_LOGS_ENABLE="1" PG_NON_DURABILITY="1"
  - INCLUDE="test_module,second_module" UNIT_TEST="1" PG_LOGS_ENABLE="1" PG_NON_DURABILITY="1" 
  - VERSION="7.0" INCLUDE="test_module,second_module" ODOO_REPO="OCA/OCB" PG_LOGS_ENABLE="1" PG_NON_DURABILITY="1"  # ODOO_REPO usage example
  # - VERSION="6.1" INCLUDE="test_module,second_module"
  - LINT_CHECK="1" TESTS="0"
  - EXCLUDE="broken_module,broken_lint" OPTIONS="--load-language=es_MX" INSTALL_OPTIONS="--load-language=es_MX"
  - INCLUDE="test_module,second_module" UNBUFFER=0
  - INCLUDE="test_module,second_module,website" PHANTOMJS_TESTS="1"

install:
  - cp -r ../maintainer-quality-tools/ $HOME
  - cp -r tests/test_repo/* ./
  - export PATH=$HOME/maintainer-quality-tools/travis:$PATH
  - LINT_CHECK="1" TESTS="1" travis_install_nightly  # self_tests use pylint plugin
  - cp $HOME/maintainer-quality-tools/travis/cfg/*.cfg $TRAVIS_BUILD_DIR/travis/cfg/  # travis_install_nightly overwrite .cfg files
  - pip install coveralls  # Force install coveralls in all cases of MQT for self_test script.
  - git --git-dir=${TRAVIS_BUILD_DIR}/.git add --all  # All modules moved are modules changed to test PR changes

script:
  - coverage run --append ./travis/self_tests
  - coverage run --append ./travis/travis_run_tests 8.0  # only used if VERSION not set in env

after_success:
  - TESTS="1" LINT_CHECK="0" travis_after_tests_success
