# WARNING:
# Do not use this file as a template for you repository TravisCI configuration
# Instead use the files under the "/sample_files" directory for that purpose.
language: python

build_image: vauxoo/odoo-80-image-shippable-auto
commit_container: cowardvassal/vauxoo-dev

python:
  - "2.7"

addons:
  apt:
    packages:
      - expect-dev  # provides unbuffer utility
      - python-lxml  # because pip installation is slow
      - python-simplejson
      - python-serial
      - python-yaml

virtualenv:
  system_site_packages: true

env:

  global:
  - VERSION="8.0" TESTS="1" LINT_CHECK="0"

  matrix:
  - INCLUDE="broken_module" SERVER_EXPECTED_ERRORS="1"  # test errors are detected
  - EXCLUDE="broken_module" OPTIONS="--log-level=debug" INSTALL_OPTIONS="--log-level=info"
  - INCLUDE="test_module,second_module" UNIT_TEST="1"
  - VERSION="7.0" INCLUDE="test_module,second_module" ODOO_REPO="OCA/OCB"  # ODOO_REPO usage example
    # - VERSION="6.1" INCLUDE="test_module,second_module"  # Vauxo don't suppport 6.1 anymore
  - LINT_CHECK="1" TESTS="0"

install:
  - cp -r ../maintainer-quality-tools/ $HOME
  - mv tests/test_repo/* ./
  - export PATH=$HOME/maintainer-quality-tools/travis:$PATH
  - travis_install_nightly 8.0 # only used if VERSION not set in env

script:
  - travis_run_tests 8.0  # only used if VERSION not set in env

#after_success:
#  coveralls
