# WARNING:
# Do not use this file as a template for you repository TravisCI configuration
# Instead use the files under the "/sample_files" directory for that purpose.
language: python
sudo: false
cache:
  apt: true
  directories:
    - $HOME/.cache/pip

build_image: vauxoo/odoo-80-image-shippable-auto
commit_container: cowardvassal/vauxoo-dev

python:
  - "2.7"

addons:
  apt:
    packages:
      - expect-dev  # provides unbuffer utility

virtualenv:
  system_site_packages: true

env:

  global:
  - VERSION="8.0" TESTS="1" LINT_CHECK="0"
  - PYLINT_ODOO_JSLINTRC="$HOME/maintainer-quality-tools/travis/cfg/.jslintrc"
  matrix:
  - INCLUDE="test_module,second_module,website" PHANTOMJS_TESTS="1"

install:
  - export PATH=$HOME/maintainer-quality-tools/travis:$PATH

script:
  - |
    echo "printing debug information"
    echo "Environment variables:"
    env
    echo "----------"
    echo "git remote -v:"
    git remote -v
    echo "----------"
    echo "git branch -v:"
    git branch -v
    echo "----------"
    echo "git status:"
    git status
    echo "----------"

after_success:
  - TESTS="1" LINT_CHECK="0" travis_after_tests_success
