#!/usr/bin/env python
import os
import subprocess
import sys

from getaddons import get_modules


root_dir = os.path.dirname(os.path.abspath(__file__))
flake8_config_dir = os.path.join(root_dir, 'cfg')

status = 0

include = os.environ.get('INCLUDE_LINT', '').split(' ')
paths = [os.path.abspath('.')] + include
modules = []
for path in paths:
    modules.extend(os.path.join(path, mod) for mod in get_modules(path))

for addon in modules:
    status += subprocess.call(['flake8', addon,
                               '--config=%s/travis_run_flake8__init__.cfg' %
                               flake8_config_dir])
    status += subprocess.call(['flake8', addon,
                               '--config=%s/travis_run_flake8.cfg' %
                               flake8_config_dir])

sys.exit(0 if status == 0 else 1)
