#!/bin/bash

MODULES_TO_TEST=$TRAVIS_BUILD_DIR
PYLINT_CONFIG_DIR="$(dirname $0)/cfg"

# Fix pylint path. More info: https://www.mail-archive.com/code-quality@python.org/msg00294.html
export PYTHONPATH=${PYTHONPATH}:${MODULES_TO_TEST}
touch $MODULES_TO_TEST/__init__.py

# Set openerp in python path to fix "import" from addons
if [ "x${VERSION}" == "x" ] ; then
    VERSION="${1}"
    echo "WARNING: no env variable set for VERSION. Using '${1}'."
fi

: ${ODOO_REPO:="odoo/odoo"}  # default value, if not set
IFS="/" read -a REPO <<< "${ODOO_REPO}"
echo $(dirname ${BASH_SOURCE[0]})
export PYTHONPATH=${PYTHONPATH}:"${HOME}/${REPO[1]}-${VERSION}":"$(dirname ${BASH_SOURCE[0]})/travis"

$(dirname ${BASH_SOURCE[0]})/mk_ln_addons
#ls -la ${HOME}/${REPO[1]}-${VERSION}/openerp/addons

if [ "x${INCLUDE_CHANGED}" == "x1"  ]
then
    echo "Get modules changed"
    MODULES_TO_TEST=$(python -c "import test_server;print ' '.join(test_server.get_addons_to_check('${TRAVIS_BUILD_DIR}', '${INCLUDE}', '${EXCLUDE}', '${INCLUDE_CHANGED}' == '1', '${TRAVIS_BRANCH}'))")
fi

echo "Modules to test: "${MODULES_TO_TEST}

#run pylint command
(cd ${TRAVIS_BUILD_DIR} && pylint --rcfile=${PYLINT_CONFIG_DIR}/travis_run_pylint.cfg ${MODULES_TO_TEST} -d C0103,F0401,I0011)
pylint_status=$?
exit $((${pylint_status}))
