#!/usr/bin/env python

import os

import coverage
from coveralls import cli as coveralls_cli
from lxml import etree


if (os.environ.get('TESTS', '1') == '1' and
        not os.environ.get('LINT_CHECK') == '1'
        and os.environ.get('SHIPPABLE', False) != 'true'):
    coverage.main(["report", "--show-missing"])
    exit(coveralls_cli.main(argv=None))
