#!/bin/bash

set -v

pwd
ls .

echo $TRAVIS_BUILD_DIR
ls $TRAVIS_BUILD_DIR

echo $HOME
ls $HOME

echo $ODOO_REPO
ls $ODOO_REPO

pylint --rcfile=../maintainer-quality-tools/travis/cfg/travis_run_pylint.cfg odoo-$VERSION/openerp
pylint_status=$?
exit $((${pylint_status}))
